server:
  port: 8002
spring:
  application:
    name: GLYDL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yqfk?serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: root
  jpa:
    database: MySql
    show-sql: true
aliyun:
  sms:
    accessKeyId: LTAI4G4LyM5SwtQBKjcijas2
    accessKeySecret: nanXZMVYbwiW26nWOHBPLeF25QpmhW
    sign_name: QST2020
    template_code: SMS_203717866